language: node_js

os:
  - linux

node_js:
  - "11"
  - "12"
  - "13"

install:
  - npm install
  - npm run test:install
  - npm install -g codecov

stages:
  - test
  - name: deploy
    if: (branch = master) AND (NOT (type IN (pull_request)))
  - gh-pages
    if: (branch = master OR branch = playground) AND (NOT (type IN (pull_request)))

jobs:
  include:
    - stage: test
      name: "Run test scripts"
      node_js: "8.6.0"
      script:
        - npm run test
        - codecov

    - stage: deploy
      name: "Release npm package"
      node_js: "12"
      script: echo "Release npm package..."
      deploy:
        provider: npm
        email: 1558267774@qq.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master

    - stage: gh-pages
      name: "Deploying to GitHub Pages"
      node_js: "12"
      github_token: $GITHUB_TOKEN
      skip_cleanup: true
      local_dir: playground/dist
      script:
        - npm run pg:install
        - npm run pg:build

notifications:
  email: false
