language: node_js

os:
  - linux

node_js:
  - "8.6.0"
  - "12"

stages:
  - test
  - name: releaseNpm
    if: branch = master

jobs:
  include:
    - stage: test
      name: "Run test scripts"
      node_js:
        - "8.6.0"
        - "12"
      install:
        - npm install
        - npm run test:install
        - npm install -g codecov
      script:
        - npm run test
        - codecov

    - stage: releaseNpm
      name: "Release npm package"
      node_js: "12"
      script:
        - echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: 1558267774@qq.com
        api_key: "$NPM_TOKEN"
        on:
          branch: master

notifications:
  slack:
    if: branch = master
