language: node_js

node_js:
  - "8.6.0"

branches:
  only:
    - master

install:
  - npm install
  - npm run test:install
  - npm install -g codecov

script:
  - npm run test
  - codecov

notifications:
  email: false
